all:constandconstruct fock_funcs implictandexplict oop_1
constandconstruct:constandconstruct.cpp
	g++ -o $@ -g $<
fock_funcs:fock_funcs.cpp
	g++ -o $@ -g $<
implictandexplict:implictandexplict.cpp
	g++ -o $@ -g $<
oop_1:oop_1.cpp
clean:
	rm -rf constandconstruct fock_funcs implictandexplict oop_1
